TRANSACTION_COST = 0.001
#TRANSACTION_COST = 0
BUY = 1
SELL = -1
HOLD = 0
ALL = "all"
TRAIN = "train"
TEST = "test"
TRAINTEST = "trainTest"
PRICE = "price"
RETURN = "return"
DATETIME = "dateTime"
SAMEORDERSTR = "Same order as last time"